# Generated by Django 5.1.2 on 2025-03-30 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Введите корректный email."
                            )
                        ],
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефон должен быть в формате +7(XXX)-XXX-XX-XX.",
                                regex="^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "other_service_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание другой услуги"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("card", "Карта")],
                        max_length=4,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В работе"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="in_progress",
                        max_length=11,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.services",
                        verbose_name="Выбор услуги",
                    ),
                ),
            ],
        ),
    ]
