# Generated by Django 5.1.2 on 2025-03-30 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="phone",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате +7(XXX)-XXX-XX-XX.",
                        regex="^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
