# Generated by Django 5.1.2 on 2025-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0002_alter_requests_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина отмены"
            ),
        ),
    ]
